# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-15 15:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=50)),
                ('question_no', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_name', models.CharField(default='host', max_length=10)),
                ('play_allowed', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_no', models.IntegerField()),
                ('difficulty_level', models.IntegerField()),
                ('content', models.CharField(max_length=50)),
                ('answer', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User_Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=50)),
                ('name_1', models.CharField(max_length=50)),
                ('idno_1', models.CharField(max_length=12)),
                ('phone_1', models.BigIntegerField(null=True)),
                ('email_1', models.EmailField(max_length=254)),
                ('name_2', models.CharField(blank=True, max_length=50)),
                ('idno_2', models.CharField(blank=True, max_length=12)),
                ('phone_2', models.BigIntegerField(blank=True, null=True)),
                ('email_2', models.EmailField(blank=True, max_length=254, null=True)),
                ('attempted_questions', models.CharField(default='0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0', max_length=39)),
                ('correct_questions', models.CharField(default='0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0', max_length=39)),
                ('allowed_to_play', models.IntegerField(default=0)),
                ('population', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
